### ISSUE TITLE
CPP to PHP non-compatible

### ISSUE THREAD

**Issue by Valduis4** [KyleBanks/XOREncryption#21]
I am trying to encrypt something on Cpp and decrypt it in PHP but they won't work.  Any tips, they are the same key.

**Comment by Valduis4** [comment]
text 2Timothy1:7
`? #:6fhx cpp encryption
`>? #:6fhx php encryption of same text

**Comment by zorftw** [comment]
PHP does not support multi-byte strings, so make sure your string is encoded using UTF-8 or similar

**Comment by Valduis4** [comment]
How do you do that?
Also random letters like sdffdsfa work.  Is there a reason the first would not work?

**Comment by Valduis4** [comment]
For anyone in the future this is the cpp code to fix it
`int size = MultiByteToWideChar(CP_ACP, MB_COMPOSITE, string.c_str(),
                                string.length(), nullptr, 0);
    std::wstring utf16_str(size, '\0');
    MultiByteToWideChar(CP_ACP, MB_COMPOSITE, string.c_str(),
                        string.length(), &utf16_str[0], size);

    int utf8_size = WideCharToMultiByte(CP_UTF8, 0, utf16_str.c_str(),
                                        utf16_str.length(), nullptr, 0,
                                        nullptr, nullptr);
    std::string utf8_str(utf8_size, '\0');
    WideCharToMultiByte(CP_UTF8, 0, utf16_str.c_str(),
                        utf16_str.length(), &utf8_str[0], utf8_size,
                        nullptr, nullptr);
std::cout<<"UTF-8 string: "<<utf8_str<<std::endl;`
